[project]
name = 'another-ape-contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.another-ape]
path = 'contracts/another-ape.clar'
clarity_version = 2
epoch = 2.5

[contracts.sip009]
path = 'contracts/sip009.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
